// class is to write the functions in a class instead of writing function in object note that class is used to organize our code
export class Cart {
    // cart item mndun # its mean cartItem is public property can be used outside the class
    cartItems;
    //# means that local storageKey is a private property can be used only inside the class
    #localStorageKey;
    // this constructor let us setup code inside the classes
    constructor(localStorageKey) { // mn dun l constructor badna n7ut heda l code barra ta7t const cart = new Cart()  lm3arefun ta7t;


        
        this.#localStorageKey = localStorageKey;
        this.#loadFromStorage();


    }
    updateDeliveryOption(productId, deliveryOptionId) {
        let matchingItem;
        this.cartItems.forEach((cartItem) => {
            if (productId === cartItem.productId) {
                matchingItem = cartItem;
            }

        })
        matchingItem.deliveryOptionId = deliveryOptionId;

        saveToLocalStorge();

    }

    #loadFromStorage() {
        //this here means cart (object name)             and this here mean localStorage key that defined above
        this.cartItems = JSON.parse(localStorage.getItem(this.#localStorageKey));

        if (!this.cartItems) {
            this.cartItems = [{
                productId: "e43638ce-6aa0-4b85-b27f-e1d07eb678c6",
                quantity: 1,
                deliveryOptionId: '3'
            }]
        }
    }
    saveToLocalStorge() {
        localStorage.setItem(this.#localStorageKey, JSON.stringify(this.cartItems));
    }
    removeFromCart(productId) {
        const newCart = [];

        this.cartItems.forEach((cartItem) => {
            if (cartItem.productId !== productId) {
                newCart.push(cartItem);
            }
        })



        this.cartItems.cart = newCart;
        saveToLocalStorge();
    }


}


// heda l value cart-oop beru7 do8re 3al constructor le faw2

const cart = new Cart('cart-oop');


const bussnissCart = new Cart('bussniss-cart');
;

console.log(cart);

// to check if the object bussniss cart generated by Cart class you should write the following
console.log(bussnissCart instanceof Cart);// gives tru








